name: Submit tournament results
description: Paste a new tournament section and trigger a recalculation.
title: "Add results: <YYYY> <Tournament>"
labels: ["recalculate"]
body:
  - type: markdown
    attributes:
      value: |
        Paste the new tournament section below **including the header line** (e.g. `2026 Northern`).
        Use the same format as `data/TournamentResults.txt`.

  - type: textarea
    id: block
    attributes:
      label: Tournament block
      description: Paste the full block inside the code fence.
      placeholder: |
        ```text
        2026 Northern
        Non-Qualifiers
        ...
        Final
        ...
        ```
    validations:
      required: true
